// LifeOS — static icon barrel (tree-shaking-safe) — JS sibling of icons.ts
// Imports ONLY the icons actually used in templates + data.js.
// Unknown kebab names fall back to the placeholder span in Icon.vue.
import {
  Activity,
  Archive,
  ArrowLeft,
  ArrowRight,
  AlertTriangle,
  BarChart3,
  Dot,
  X,
  Battery,
  BatteryCharging,
  Bed,
  Bell,
  Bookmark,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Calendar,
  CalendarDays,
  Car,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  Circle,
  CircleDot,
  Clock,
  Cloud,
  Code,
  Columns2,
  Compass,
  Component,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Droplet,
  Edit,
  ExternalLink,
  Eye,
  File,
  FileCheck,
  FileCode,
  FileCode2,
  FileJson2,
  FileKey,
  FilePlus,
  FileText,
  Film,
  Flame,
  FlaskConical,
  Folder,
  FolderOpen,
  FolderTree,
  FolderUp,
  Footprints,
  Frame,
  Gamepad2,
  GitBranch,
  Globe,
  Grid3x3,
  GripVertical,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  KeyRound,
  Lamp,
  Laptop,
  Layers,
  Library,
  Lightbulb,
  Link,
  ListTodo,
  Lock,
  LogIn,
  Mail,
  Megaphone,
  MemoryStick,
  MessageCircle,
  MessageSquare,
  Monitor,
  Moon,
  MousePointer2,
  Move,
  Music,
  Palette,
  PenTool,
  Phone,
  PlayCircle,
  Plug,
  Plus,
  Radio,
  Receipt,
  RefreshCw,
  RotateCcw,
  Route,
  Router,
  Scale,
  ScanLine,
  Search,
  SearchCheck,
  Send,
  Server,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sofa,
  Speaker,
  Sparkles,
  Sprout,
  Square,
  Star,
  Sun,
  Sunrise,
  Tablet,
  Target,
  Terminal,
  Thermometer,
  TrendingUp,
  Trees,
  Trophy,
  Trash2,
  Tv,
  Type,
  User,
  UserCheck,
  UserPlus,
  UserSearch,
  Users,
  Users2,
  Upload,
  Utensils,
  Video,
  Wallet,
  Waves,
  Wifi,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from "@lucide/vue";

// kebab-case name → Lucide component
export const icons = {
  "activity":           Activity,
  "alert-triangle":     AlertTriangle,
  "archive":            Archive,
  "arrow-left":         ArrowLeft,
  "arrow-right":        ArrowRight,
  "bar-chart-3":        BarChart3,
  "battery":            Battery,
  "battery-charging":   BatteryCharging,
  "bed":                Bed,
  "bell":               Bell,
  "book-open":          BookOpen,
  "bookmark":           Bookmark,
  "bot":                Bot,
  "boxes":              Boxes,
  "brain":              Brain,
  "calendar":           Calendar,
  "calendar-days":      CalendarDays,
  "check":              Check,
  "check-circle":       CheckCircle,
  "chevron-down":       ChevronDown,
  "chevron-left":       ChevronLeft,
  "chevron-right":      ChevronRight,
  "chevrons-right":     ChevronsRight,
  "circle":             Circle,
  "circle-dot":         CircleDot,
  "clock":              Clock,
  "cloud":              Cloud,
  "code":               Code,
  "columns-2":          Columns2,
  "compass":            Compass,
  "component":          Component,
  "cpu":                Cpu,
  "credit-card":        CreditCard,
  "database":           Database,
  "dollar-sign":        DollarSign,
  "dot":                Dot,
  "download":           Download,
  "droplet":            Droplet,
  "edit":               Edit,
  "external-link":      ExternalLink,
  "eye":                Eye,
  "file":               File,
  "file-check":         FileCheck,
  "file-code":          FileCode,
  "file-code-2":        FileCode2,
  "file-json-2":        FileJson2,
  "file-key":           FileKey,
  "file-plus":          FilePlus,
  "file-text":          FileText,
  "film":               Film,
  "flame":              Flame,
  "flask-conical":      FlaskConical,
  "folder":             Folder,
  "folder-open":        FolderOpen,
  "folder-tree":        FolderTree,
  "folder-up":          FolderUp,
  "footprints":         Footprints,
  "frame":              Frame,
  "gamepad-2":          Gamepad2,
  "git-branch":         GitBranch,
  "globe":              Globe,
  "grid-3x3":           Grid3x3,
  "grip-vertical":      GripVertical,
  "hard-drive":         HardDrive,
  "headphones":         Headphones,
  "heart":              Heart,
  "heart-pulse":        HeartPulse,
  "history":            History,
  "home":               Home,
  "image":              Image,
  "inbox":              Inbox,
  "info":               Info,
  "key":                Key,
  "key-round":          KeyRound,
  "lamp":               Lamp,
  "laptop":             Laptop,
  "layers":             Layers,
  "library":            Library,
  "lightbulb":          Lightbulb,
  "link":               Link,
  "list-todo":          ListTodo,
  "lock":               Lock,
  "log-in":             LogIn,
  "mail":               Mail,
  "megaphone":          Megaphone,
  "memory-stick":       MemoryStick,
  "message-circle":     MessageCircle,
  "message-square":     MessageSquare,
  "monitor":            Monitor,
  "moon":               Moon,
  "mouse-pointer-2":    MousePointer2,
  "move":               Move,
  "music":              Music,
  "palette":            Palette,
  "pen-tool":           PenTool,
  "phone":              Phone,
  "play-circle":        PlayCircle,
  "plug":               Plug,
  "plus":               Plus,
  "radio":              Radio,
  "receipt":            Receipt,
  "refresh-cw":         RefreshCw,
  "rotate-ccw":         RotateCcw,
  "route":              Route,
  "router":             Router,
  "car":                Car,
  "scale":              Scale,
  "scan-line":          ScanLine,
  "search":             Search,
  "search-check":       SearchCheck,
  "send":               Send,
  "server":             Server,
  "settings":           Settings,
  "settings-2":         Settings2,
  "share-2":            Share2,
  "shield":             Shield,
  "shield-alert":       ShieldAlert,
  "shield-check":       ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  "smartphone":         Smartphone,
  "sofa":               Sofa,
  "speaker":            Speaker,
  "sparkles":           Sparkles,
  "sprout":             Sprout,
  "square":             Square,
  "star":               Star,
  "sun":                Sun,
  "sunrise":            Sunrise,
  "tablet":             Tablet,
  "target":             Target,
  "terminal":           Terminal,
  "thermometer":        Thermometer,
  "trash-2":            Trash2,
  "trending-up":        TrendingUp,
  "trees":              Trees,
  "trophy":             Trophy,
  "tv":                 Tv,
  "type":               Type,
  "upload":             Upload,
  "user":               User,
  "user-check":         UserCheck,
  "user-plus":          UserPlus,
  "user-search":        UserSearch,
  "users":              Users,
  "users-2":            Users2,
  "utensils":           Utensils,
  "video":              Video,
  "wallet":             Wallet,
  "waves":              Waves,
  "wifi":               Wifi,
  "x":                  X,
  "zap":                Zap,
  "zap-off":            ZapOff,
  "zoom-in":            ZoomIn,
  "zoom-out":           ZoomOut,
};
